language: php
matrix:
  fast_finish: true
  include:
  - php: 7.0
    env: PHP_L=1
  - php: 5.3
    env: PHP_L_OLD=1
  - php: 5.4
    env: PHP_L_OLD=1
  - php: 5.5
    env: PHP_L=1
  - php: 5.6
    env: PHP_L=1 PHPCS=1
  - php: hhvm
    env: PHP_L_OLD=1

  allow_failures:
  - php: 7.0
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $PHP_L == 1 ]]; then find . -path './vendor' -prune -o -name "*.php" -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected' ; test $? -eq 1; fi
  - if [[ $PHP_L_OLD == 1 ]]; then find . -regextype posix-extended -regex "\./(lib/influxdb-php|vendor)" -prune -o -name "*.php" -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected' ; test $? -eq 1; fi
  - if [[ $PHP_CS == 1 ]]; then vendor/bin/phpcs -n -p --colors --extensions=php --standard=PSR2 --ignore=html/lib/* .; fi
