language: php
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
    env:
      PHP_CS=1
      EXECUTE_BUILD_DOCS=true
  - php: hhvm

  allow_failures:
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $EXECUTE_BUILD_DOCS == "true" && bash scripts/deploy-docs.sh

script:
  - php scripts/pre-commit.php -l
  - if [[ $PHP_CS == 1 ]]; then php scripts/pre-commit.php -p -s; fi
  - phpunit
