language: php
matrix:
  fast_finish: true
  include:
  - php: 7.0
  - php: 5.3
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.4
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.5
    env:
      SKIP_STYLE_CHECK=1
  - php: 5.6
    env:
      SKIP_STYLE_CHECK=1
      EXECUTE_BUILD_DOCS=true
  - php: hhvm
    env:
      SKIP_STYLE_CHECK=1

  allow_failures:
  - php: hhvm

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $EXECUTE_BUILD_DOCS == "true" && bash scripts/deploy-docs.sh

script:
  - php scripts/pre-commit.php -p -l
  - php scripts/pre-commit.php -p -s
  - phpunit
