site_name: LibreNMS Documentation
theme: mkdocs
docs_dir: doc
site_dir: out
site_url: http://docs.librenms.org
markdown_extensions:
    - pymdownx.superfences
extra_css:
    - librenms.css
include_next_prev: false
site_author: LibreNMS
site_description: LibreNMS user and developer documentation
repo_url: https://github.com/librenms/librenms
repo_name: GitHub
